name: Output data
on:
  issues:
    types:
      - opened
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output github context
        run: echo "Issue triggered"
          \n Title- "${{ github.event.issue.title }}"
          \n Body- "${{ github.event.issue.body }}"
