name: deploy project
on:
  issues:
    types:
      - opened
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output github context
        run: echo "Issue triggered"
          echo Title- "${{ github.event.title }}"
          echo Body- "${{ github.event.body }}"
